version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=mex_cloud
      - JWT_SECRET=secret
      - DEFAULT_ADMIN_USER=admin
      - DEFAULT_ADMIN_PASS=123456
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mex_cloud
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mex_cloud_mysql_data
